/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class Efetuar_Pedido_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Efetuar_Pedido_GUI
     */
    public Efetuar_Pedido_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        num_mesa_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numeros_pedidos_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        observacao_txt = new javax.swing.JTextField();
        efetuar_pedido_btn = new org.edisoncor.gui.button.ButtonAction();
        jLabel5 = new javax.swing.JLabel();
        garcom_txt = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        vPed_btn = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        efetP_btn = new javax.swing.JMenuItem();
        consultP_btn = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        exit_btn = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg-sys.png"))); // NOI18N
        panelImage1.setLayout(null);

        num_mesa_txt.setForeground(new java.awt.Color(102, 102, 102));
        num_mesa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_mesa_txtActionPerformed(evt);
            }
        });
        panelImage1.add(num_mesa_txt);
        num_mesa_txt.setBounds(350, 70, 170, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mesa:");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(350, 50, 38, 17);

        numeros_pedidos_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeros_pedidos_txtActionPerformed(evt);
            }
        });
        panelImage1.add(numeros_pedidos_txt);
        numeros_pedidos_txt.setBounds(70, 70, 250, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Números dos Pedidos:");
        panelImage1.add(jLabel2);
        jLabel2.setBounds(70, 50, 142, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Observação:");
        panelImage1.add(jLabel4);
        jLabel4.setBounds(70, 170, 81, 17);

        observacao_txt.setForeground(new java.awt.Color(102, 102, 102));
        observacao_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observacao_txtActionPerformed(evt);
            }
        });
        panelImage1.add(observacao_txt);
        observacao_txt.setBounds(70, 190, 452, 30);

        efetuar_pedido_btn.setText("Efetuar Pedido");
        efetuar_pedido_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuar_pedido_btnActionPerformed(evt);
            }
        });
        panelImage1.add(efetuar_pedido_btn);
        efetuar_pedido_btn.setBounds(70, 270, 149, 35);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Garçom:");
        panelImage1.add(jLabel5);
        jLabel5.setBounds(70, 110, 60, 17);

        garcom_txt.setForeground(new java.awt.Color(102, 102, 102));
        garcom_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garcom_txtActionPerformed(evt);
            }
        });
        panelImage1.add(garcom_txt);
        garcom_txt.setBounds(70, 130, 450, 30);

        vPed_btn.setText("Cozinha");

        jMenuItem1.setText("Ver Pedidos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        vPed_btn.add(jMenuItem1);

        jMenuBar1.add(vPed_btn);

        jMenu1.setText("Garçom");

        efetP_btn.setText("Efetuar Pedido");
        efetP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetP_btnActionPerformed(evt);
            }
        });
        jMenu1.add(efetP_btn);

        consultP_btn.setText("Consultar Pedido");
        consultP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultP_btnActionPerformed(evt);
            }
        });
        jMenu1.add(consultP_btn);

        jMenuItem2.setText("Menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Ajuda");

        jMenuItem4.setText("Arquivo de ajuda");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        exit_btn.setText("Fechar");

        jMenuItem3.setText(" Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        exit_btn.add(jMenuItem3);

        jMenuBar1.add(exit_btn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void efetP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetP_btnActionPerformed
        new Efetuar_Pedido_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_efetP_btnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Ver_Pedidos_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void num_mesa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_mesa_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_mesa_txtActionPerformed

    private void numeros_pedidos_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeros_pedidos_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeros_pedidos_txtActionPerformed

    private void observacao_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observacao_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observacao_txtActionPerformed

    private void garcom_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garcom_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_garcom_txtActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void efetuar_pedido_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuar_pedido_btnActionPerformed
        Controller.Funcoes_DAO.efetuar_pedido();
    }//GEN-LAST:event_efetuar_pedido_btnActionPerformed

    private void consultP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultP_btnActionPerformed
        new Consultar_Pedido_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_consultP_btnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Menu_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            Controller.Funcoes_DAO.abrir_arquivo_de_ajuda();
        } catch (IOException ex) {
            Logger.getLogger(Comanda_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Efetuar_Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Efetuar_Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Efetuar_Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Efetuar_Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Efetuar_Pedido_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem consultP_btn;
    private javax.swing.JMenuItem efetP_btn;
    private org.edisoncor.gui.button.ButtonAction efetuar_pedido_btn;
    private javax.swing.JMenu exit_btn;
    public static javax.swing.JTextField garcom_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public static javax.swing.JTextField num_mesa_txt;
    public static javax.swing.JTextField numeros_pedidos_txt;
    public static javax.swing.JTextField observacao_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JMenu vPed_btn;
    // End of variables declaration//GEN-END:variables
}
